name: web
description: >-
  Lightweight DOM and JS bindings built around JS static interop.
version: 0.2.3-wip

repository: https://github.com/dart-lang/web

environment:
  sdk: ">=3.2.0-194.0.dev <4.0.0"

dev_dependencies:
  args: ^2.4.0
  code_builder: ^4.4.0
  dart_flutter_team_lints: ^2.0.0
  dart_style: ^2.2.4
  io: ^1.0.4
  path: ^1.8.3
  test: ^1.22.2
