name: web
version: 0.0.1-dev

repository: https://github.com/dart-lang/web

environment:
  sdk: ">=3.0.0-231.0.dev <3.1.0"

dependencies:
  js: ^0.6.7

dev_dependencies:
  dart_flutter_team_lints: ^0.1.0
  test: ^1.22.2
