name: web_generator
publish_to: none # internal only for now
version: 1.0.0-wip
description: Generator scripts for package:web.
repository: https://github.com/dart-lang/web

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^7.4.0
  args: ^2.4.0
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.8
  code_builder: ^4.10.0
  collection: ^1.18.0
  dart_flutter_team_lints: ^3.0.0
  dart_style: ^3.0.0
  io: ^1.0.4
  package_config: ^2.1.1
  path: ^1.8.3
  pub_semver: ^2.1.5
  test: ^1.24.4
