name: web_generator
publish_to: none # internal only for now
version: 1.0.0-wip
description: Generator scripts for package:web.
repository: https://github.com/dart-lang/web

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^9.0.0
  args: ^2.5.0
  code_builder: ^4.10.0
  collection: ^1.19.1
  convert: ^3.1.2
  dart_style: ^3.1.3
  io: ^1.0.4
  meta: ^1.17.0
  package_config: ^2.1.1
  path: ^1.9.0
  pub_semver: ^2.1.5
  yaml: ^3.1.3

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.27.0
  web: ^1.1.1
