name: web
version: 1.1.1
description: Lightweight browser API bindings built around JS interop.
repository: https://github.com/dart-lang/web

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  path: ^1.8.3
  test: ^1.24.4
